name: univs
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^8.1.3
  cloud_firestore: ^4.17.3
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dash_chat_2: ^0.0.20
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.25.4
  firebase_database: ^10.4.5
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.4
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  iconly: ^1.0.1
  image_picker: ^1.1.1
  intl: ^0.18.1
  json_annotation: ^4.9.0
  loader_overlay: ^4.0.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  shimmer: ^3.0.0

dev_dependencies:
  auto_route_generator: ^8.0.0

  # gen
  build_runner: ^2.4.9

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

  # state management
  provider: ^6.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/others/
