// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWCWFTnYMhSLUMsNw_fwgDBVSBiTBgKwk',
    appId: '1:759701193433:web:d2894ccd758312f429f4c8',
    messagingSenderId: '759701193433',
    projectId: 'univs-93961',
    authDomain: 'univs-93961.firebaseapp.com',
    storageBucket: 'univs-93961.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzrE9kB-mMS3-RfduQU56u1yKO4HPfUP4',
    appId: '1:759701193433:android:dff0766b8b0783de29f4c8',
    messagingSenderId: '759701193433',
    projectId: 'univs-93961',
    storageBucket: 'univs-93961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF3y3lYsR5Wdf_GY9bc2B-fciZQelVmCI',
    appId: '1:759701193433:ios:9e454055875b65d629f4c8',
    messagingSenderId: '759701193433',
    projectId: 'univs-93961',
    storageBucket: 'univs-93961.appspot.com',
    iosBundleId: 'com.example.univs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF3y3lYsR5Wdf_GY9bc2B-fciZQelVmCI',
    appId: '1:759701193433:ios:7f86ad165ec682fd29f4c8',
    messagingSenderId: '759701193433',
    projectId: 'univs-93961',
    storageBucket: 'univs-93961.appspot.com',
    iosBundleId: 'com.example.univs.RunnerTests',
  );
}
